AllCops:
  # RunRailsCops: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IndentationWidth:
  Width: 2

Style/Semicolon:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
